# Built with Jekyll 3.2.0

# Setup
title:               Ghetto Fiction, 1880-1920 
tagline:             'Using Ed, a Jekyll theme to create minimal editions'
description:         'Text description here'
url:                 'http://jeanleecole.github.io/ed'
baseurl:             '/ed'

# About/contact
author:
  name:              Jean Lee Cole
  url:               https://twitter.com/profjlc
  email:             jlcole@loyola.edu

# Permalinks

permalink: pretty
permalink: /:title/

# Set encoding to UTF-8
encoding: utf-8

# Collections for texts
collections:
  texts:
    output: true

# Markdown specs
markdown: kramdown

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  footnote_backlink: "&#x21a9;&#xfe0e;"
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Custom vars
version:             0.0.6

# Exclusions from the final site
exclude: [optional, vendor]


